# Generated by Django 5.1.6 on 2025-04-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskslist',
            name='list_name',
        ),
        migrations.AddField(
            model_name='taskslist',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskslist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
