# Generated by Django 5.1.6 on 2025-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_taskslist_list_name_taskslist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskslist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
