# Generated by Django 5.1.6 on 2025-04-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_taskslist_description_alter_taskslist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
