# Generated by Django 5.1.6 on 2025-04-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_state_alter_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Unspecified', max_length=100),
            preserve_default=False,
        ),
    ]
