# Generated by Django 5.1.6 on 2025-06-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_category_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
