# Generated by Django 5.1.6 on 2025-06-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_taskslist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
