# Generated by Django 5.1.6 on 2026-03-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_taskslist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='taskslist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
