# Generated by Django 5.1.6 on 2026-03-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_task_priority_alter_taskslist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='Unspecified', max_length=100),
        ),
    ]
